server.port: 7001

logging:
  level:
    root: INFO
    arthur.kim: DEBUG

spring:
  data:
    mongodb:
      auto-index-creation: true
---
# spring.profiles: docker
spring:
  profiles: docker
  data:
    mongodb:
      auto-index-creation: true
server.port: 8080