version: '2.1'

services:
  product:
    build: microservices/product-service
    mem_limit: 350m
    environment:
       - SPRING_PROFILES_ACTIVE=docker
         
  recommendation:
    build: microservices/recommendation-service
    mem_limit: 350m
    ports:
       - "8082:8080"
    environment:
       - SPRING_PROFILES_ACTIVE=docker

  review:
    build: microservices/review-service
    mem_limit: 350m
    ports:
       - "8081:8080"
    environment:
       - SPRING_PROFILES_ACTIVE=docker

  product-composite:
    build: microservices/product-composite-service
    mem_limit: 350m
    ports:
       - "8080:8080"
    environment:
       - SPRING_PROFILES_ACTIVE=docker
    links:
       - product
       - recommendation
       - review

  # $ mongo
  mongodb: 
    image: mongo:3.6.9
    mem_limit: 350m
    ports:
      - "27017:27017"
    command: mongod --smallfiles

  # $ mysql -uroot -h127.0.0.1 -p
  mysql:
    image: mysql:5.7
    mem_limit: 350m
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpwd
      - MYSQL_DATABASE=review-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uuser", "-ppwd", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10


  

