server.port: 7001

spring.data.mongodb:
  auto-index-creation: true

spring.cloud.stream:
  defaultBinder: kafka
  default.contentType: application/json
  bindings.input:
    destination: products
    group: productsGroup

spring.cloud.stream.binding.input.consumer:
  maxAttempt: 3
  backOffInitialInterval: 500
  backOffMacInterval: 1000
  backOffMultiplier: 2.0

spring.cloud.stream.rabbit.binding.input.consumer:
  autoBindDlq: true
  republishToDlq: true

spring.cloud.stream.kafka.binding.input.consumer:
  enableDlq: true

spring.cloud.stream.kafka.binder:
  brokers: 127.0.0.1
  defaultBrokerPort: 9092

# spring.rabbitmq:
#   host: 127.0.0.1
#   port: 5672
#   username: guest
#   password: guest

logging:
  level:
    root: INFO
    arthur.kim: DEBUG

---
spring:
  config.activate.on-profile: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
      database: product-db

server.port: 8080
