server.port: 7001

logging:
  level:
    root: INFO
    arthur.kim: DEBUG
  
spring.data.mongodb:
  host: localhost
  port: 27017
  database: product-db
  auto-index-creation: true

---
spring:
  config.activate.on-profile: docker
  data:
    mongodb:
      host: mongodb

server.port: 8080