server.port: 7000

logging:
  level:
    root: INFO
    arthur.kim: DEBUG

app:
    product-service:
      host: localhost
      port: 7001
    recommendation-service:
      host: localhost
      port: 7002
    review-service:
      host: localhost
      port: 7003
